### ISSUE TITLE
Custom switch definition list ordering

### ISSUE THREAD

**Issue by moll** [AndrewRadev/switch.vim#17]
Hey,

I wanted to add a few switches for **res** <=> **req** _and_ **request** <=> **response** and did so via appending them to `g:switch_custom_definitions`:

```vim
let switch_custom_definitions =
	\ [
	\ 	["request", "response"],
	\ 	["req", "res"]
	\ ]
```

However, it turns out the shortest match wins, so **request** turns to **resuest**.

I was of course able to rewrite it via the dict mechanism and added a few `\>` in there for good measure, but how about respecting the order of those custom definitions so such common subset cases could be handled without more verbose regexps? Especially when each individual switch list does respect order. :)

**Comment by moll** [comment]
Hey again,

I keep on getting hit by this. Now with **pre** <=> **post** and **previous** <=> **next** when trying to switch between DOM's `previousSibling` and `nextSibling`. A side note: those happen to be great examples of why switching mid-word isn't bad.

Coming back to what you said before, my gut tells me that being clever with the length of the match isn't a sustainable solution. Matchers are fundamentally interdependent to each other. They're also so context dependent.

For example, I just had to wrap `\<` and `\>` around my **on** <=> **off** switches for them to not interfere with **describe** <=> **describe.only** (as I often jump to that location with `/only` in Vim). Not a big problem in this case as on/off are rarely prefixes in code (unlike "previous" above) but an example of how a generic shorter switch interfered with one I considered a more specific one nonetheless. Same given a switch **if** <=> **unless** being _less_ specific as one switching between `if (...)` `if (!(...))`.

I'd say a simple linear testing for matches is a lot simpler to comprehend. Should I then end up with interdependent alternatives (e.g one switch's n-th array element is the same as another's first) I'll start thinking about negative look-aheads. Until then, I'll just pile (sub)word pairs linearly.

I don't know about the built-in switches as I don't really use them beyond **true** <=> **false**. They don't even have to be bundled in. This is Vim after all. To each his own config. ^_^

**Comment by AndrewRadev** [comment]
I've pushed a setting called `g:switch_find_smallest_match`. Set that to 0 and the plugin will simply run through the matches in order and perform the first one. If you don't care about the built-ins, you can also set `g:switch_no_builtins` to 1 and you can build your own definitions.

Let me know if this works for you.

**Comment by moll** [comment]
Awesome. Thanks, Andrew! Trying it now.

**Comment by moll** [comment]
Seems to work beautifully! Thanks!
I'll let you know when I stumble upon harder cases that can't be solved by this.

Big ups on working on Switch.vim, too! One of the most useful plugins for me.
