### ISSUE TITLE
Simple switch

### ISSUE THREAD

**Issue by rgrinberg** [AndrewRadev/switch.vim#18]
In Erlang it's useful to switch betweeh the forms `"..."` and `<<"...">>` so I've attempted to define:

```
au FileType erlang let b:switch_custom_definitions =
            \ [
            \   'string_binaries' : {
            \     '<<"\([^"]*\)">>': '"\1"',
            \     '"\([^"]*\)"':     '<<"\1">>',
            \   }
            \ ]
```

But this doesn't work so well when I'm inside the angled bracketed quotes as it keeps adding more angle brackets. Is it possible to do this right?

**Comment by AndrewRadev** [comment]
It's been a while, and I guess this should have fixed the issue, so I'm going to close it for the moment.

**Comment by rgrinberg** [comment]
Yeah oops, I forgot to reply to this. Your work around works for me
