### ISSUE TITLE
More built-ins - or a wiki?

### ISSUE THREAD

**Issue by LFDM** [AndrewRadev/switch.vim#22]
Every once in a while I add a few custom switches for this myself. I am guessing that some of them are re-inventing the wheel, others might be useful to other people.

Adding to the built-ins is probably problematic, I am not sure - people might have very specific ideas on how to do switches themselves.

But what would be nice is to have something like a collaborative wiki, where everyone can share their custom switches. People could copy/paste them then - or take them as inspiration.

What do you think?

**Comment by AndrewRadev** [comment]
It seems like a good idea, although I wonder how many people would add switches :). I've created the [github wiki](https://github.com/AndrewRadev/switch.vim/wiki) for the project and added a switch from an old issue. If you already have some switches that you'd like to share, please do :).

**Comment by AndrewRadev** [comment]
Well, a wiki was created and there has been *a bit* of activity even :). In any case, though, I think it's time to close this issue.
