### ISSUE TITLE
Add default mapping

### ISSUE THREAD

**Issue by glittershark** [AndrewRadev/switch.vim#23]
This seems like a pretty damn cool plugin - I think it could possibly be useful enough to add a default mapping like you did for splitjoin. I nominate `gs`, because it literally does nothing (for [n] seconds, actually).

**Comment by AndrewRadev** [comment]
Hmm, you're right, `gs` doesn't seem like a particularly useful mapping. I'm not sure if people that use both splitjoin and switch might end up mixing them up, but it's probably not a huge risk.

I'll tweet about it and see if anybody has strongs opinions on the topic, and I'll introduce the mapping in a few days.

**Comment by glittershark** [comment]
:+1:

**Comment by AndrewRadev** [comment]
Doesn't seem like there's a lot of interest in a different mapping. I've added the mapping and changed the docs. `gs` is now the default switch mapping. Thanks for the push :).
