### ISSUE TITLE
Request: function() to var function= in JavaScript

### ISSUE THREAD

**Issue by firedev** [AndrewRadev/switch.vim#26]
Hi,

It would be great if it could switch
```js
function whatever() {
}
```
to
```js
var whatever = function() {
}
```

Thanks.

**Comment by AndrewRadev** [comment]
This seems like a really good idea, I've done this quite often in the past. Thank you for bringing it up :).

I've pushed a commit that should implement this, could you test it?

**Comment by firedev** [comment]
Oh yeah, just what the doctor ordered. Thanks! 

Installed a better JS linter and it's hammering me all the time about these functions. I made a macro but then I can't have macros for everything.

**Comment by firedev** [comment]
Hey, one more thing, it would be great if it could revert variable to function if var is omitted. This way I could transform:
```
some = function() {
```
with `--`
into:
```
var some = function() {
```

**Comment by AndrewRadev** [comment]
Seems reasonable, the `var` doesn't need to be there anyway. Just pushed a commit that should implement this.

**Comment by firedev** [comment]
Hi, sorry, me again. I am refactoring a bunch of code and I need to convert:
```js
it('does something, () => {
...
})
```
into
```
it('does something, function() {
...
})
```
Switch doesn't do anything. Guess I can use `:%s` though.

**Comment by AndrewRadev** [comment]
Hm, that's odd, it seems to work just fine for me. Although it only works with my cursor on the `()`. You might want to do an `f(` to jump there first. Also, check that you have the latest version from master, I think it's a feature I recently implemented.
