### ISSUE TITLE
Preserve casing

### ISSUE THREAD

**Issue by moll** [AndrewRadev/switch.vim#28]
Hey,

I've got quite a list of antonyms set up. Occasionally, those words occur in camel case inside other words. E.g. `findFirst` <=> `findLast` with `first` and `last` being set up as Switch.vim definitions. It'd be great if the casing be preserved when switching. Same when switch constants: `FIRST` and `LAST`.

Thanks!

**Comment by AndrewRadev** [comment]
I don't think there's any way to "preserve case" automatically for all situations. If nothing else, you might actually *want* to change the case. A much longer discussion on the topic starts [here](https://github.com/AndrewRadev/switch.vim/issues/1#issuecomment-8469462).

Generally, I'd just recommend that you triplicate your definitions with lowercase, titlecase and uppercase versions. Considering you have a large list, I guess you'd prefer some easier way to do that, so maybe something like what I suggest in that thread:

``` vim
let g:switch_definitions =
      \ [
      \   ['normalize_case', ['true', 'false']]
      \ ]
```

Though, I'm not sure how relevant this proposal is. Maybe more like:

``` vim
let g:switch_definitions =
      \ [
      \   switch#NormalizedCase(['true', 'false'])
      \ ]
```

Or something. Of course, I'd have to actually get around to implementing something like that. What do you think of the idea?

**Comment by moll** [comment]
Ah, okay, I can imagine that someone might want, depending on the language, to switch between capitalized and non-capitalized strings. Fair enough.

I don't have a strong preference to either option. The former might lend itself to easier scripting, but if the latter isn't noticably slower to call hundreds of times per Vim startup, go with which you believe to be better.

**Comment by moll** [comment]
The more switches I have in my `vimrc`, the less VimL is suitable for them. :P
Fortunately the switch structures are plain arrays and maps, which means I can move them to a JSON file. Mentioning this that if you go with helper methods, then loading switches from JSON won't be that easy.

Just in case: I use a random JSON parser in Vim to load bigger data structures, so I'm not talking about adding JSON support to Switch.vim itself. ;)

**Comment by AndrewRadev** [comment]
I've implemented case normalization, in the way I explained, with the `switch#NormalizedCase` helper. The commit is 7f19508f4cf5c4550d45e3a356f70e403246c63e. If you take a look, you'll notice I've written some documentation on the helper, but also put some info on what the underlying data format is. Which means that you should be able to use this to generate the definitions from JSON as you're doing.

Could you try it out and let me know if it makes sense?

**Comment by moll** [comment]
Sweet. Will try. Thanks.

Any particular reason you went with underscore prefixed keys instead of something else? Like `$type`?

**Comment by AndrewRadev** [comment]
No particular reason. Anything I put in there could also be used as a "normal" substitution. Can't say whether one is more common than the other, but worst case scenario I guess you could do something like `{_type: 'normal', _definition: ...}`. Although if I decide to do nesting... Well, I'll think about it.

**Comment by AndrewRadev** [comment]
I think case normalization is working, so I'll go ahead and close this issue for now.

**Comment by moll** [comment]
I finally got around to tweaking my configuration to use case-insensitive matches and can confirm they work! Thank you again, Andrew from the past!
