### ISSUE TITLE
Try builtin switches _after_ custom

### ISSUE THREAD

**Issue by moll** [AndrewRadev/switch.vim#29]
Hey,

There are a couple of useful switches built in that I'd like to use, but occasionally I have a need to add a more specific override. For example, with the latest addition to switch between a JavaScript function declaration (https://github.com/AndrewRadev/switch.vim/blob/b4116f25d73ae5e98b89e7e40b625cf418e15bad/plugin/switch.vim#L105), combined with a linear search (`switch_find_smallest_match = 0`), my simpler `["function*", "function"]` fails to match.

Have you thought about first looking in the custom definitions and only then falling back to builtins? With a smallest match search it didn't matter, but with a linear search it makes more sense to me to first try possible overrides.

Cheers

**Comment by AndrewRadev** [comment]
I changed the order of switches, and I think this should do the trick. Sorry it took a while to get to this, but could you try out current master and let me know if this fixes the ordering issue?

**Comment by AndrewRadev** [comment]
I'll go ahead and close the issue for now, since I think it should be fixed. Please reopen if the problem persists.
