### ISSUE TITLE
Request: .to and .not_to in Ruby

### ISSUE THREAD

**Issue by firedev** [AndrewRadev/switch.vim#32]
Hi,

When editing tests one quite often needs to flip between `.to` and `.not_to` (or `.to_not`) in RSpec tests (`ft=ruby`). 

Also `be_truthy` and `be_falsey` similar to `true` and `false`.

Can this be added? Thanks.

**Comment by AndrewRadev** [comment]
This makes a lot of sense, although I'm not sure if we should switch to `.not_to` or `.to_not` :). Maybe I'll add an option or something, seems like something that's likely to be a global preference.

**Comment by firedev** [comment]
Oh come on, that's not important, just choose what you like best and stick with it.

**Comment by AndrewRadev** [comment]
Maybe :).

Seems like there's a different problem, though. I've already made a pattern for `expect(foo).to eq bar`. If you switch on the `expect`, it'll work just fine. I think it's a problem with the "tap" pattern taking precedence... Thinking about it, that one has pretty much never been really useful for me, so I'm wondering if I shouldn't just drop it from the plugin.

I'll think about it for a bit and figure something out.

**Comment by firedev** [comment]
I tried to do it many times, but it never occurred to me to try it on `expect`, especially considering that `expect` can easily span multiple lines. I was always trying it on `.to`, `.not_to` and `.to_not`.

**Comment by AndrewRadev** [comment]
Yeah, and that makes sense -- the `expect` variant is actually just the simple one-line form, so I should probably consider just doing something for `to` and `to_not` instead.

**Comment by AndrewRadev** [comment]
I've implemented this in master. I've settled on `not_to`, since it feels more readable to me :). Of course, switching on a `to_not` also works, turns it into `to`.

Could you try it out and let me know how it works?

**Comment by firedev** [comment]
Yep, looks like it. Thanks!
