### ISSUE TITLE
be_falsey be_truthy in Ruby

### ISSUE THREAD

**Issue by firedev** [AndrewRadev/switch.vim#33]
Hi,

Since Rspec prefers `be_falsey` and `be_truthy` instead of `be_false` and `be_true`, current behaviour doesn't really work with specs. It converts `be_falsey` to `be_truey`.

Maybe it's time to add another matcher.

**Comment by AndrewRadev** [comment]
Actually, I think I fixed this very recently in master. Could you try to update and give it another go? If it doesn't work right, I'll try to debug the issue.

**Comment by firedev** [comment]
Hehe, I've figured it out. You have to put the cursor on `be` while I was switching on `falsey` part. Okay, but I don't know, maybe backtrack a little before flipping for that matter?

**Comment by firedev** [comment]
It works if I put cursor on `a` in `be_falsey` but not if I put it on `f`, then it becomes `be_truey`

**Comment by firedev** [comment]
It works the other way around apparently - `be_truthy` converts to `be_falsey`, but that's easy I guess, there is no word `true`

**Comment by AndrewRadev** [comment]
Hmm, I see, that's a different problem. I'm not sure what to do about this. I could make the `true -> false` conversion only work for words. As in, `true`, but not `be_true` or `true_story`. I'm not sure if people use it for anything else.

**Comment by akarzim** [comment]
We only want to convert "false" to "true" if it is a whole word. The solution is to rewrite `g:switch_builtins.true_false` to match the word boundaries:

```viml
let g:switch_builtins =
    \ [
    \   {
    \     'capital_true_false': {
    \       '\C\<True\>':  'False',
    \       '\C\<False\>': 'True',
    \     },
    \     'true_false': {
    \       '\C\<true\>':  'false',
    \       '\C\<false\>': 'true',
    \     },
    \   },
    \ ]
```
