### ISSUE TITLE
Switching Ruby symbol to String excludes a trailing question or exclamation mark

### ISSUE THREAD

**Issue by tsigo** [AndrewRadev/switch.vim#34]
Example:

```ruby
foo = :bar?
baz = :qux!
```

Performing `:Switch` on `bar` and `qux`, I'd expect to get

```ruby
foo = "bar?"
baz = "qux!"
```

but instead I get

```ruby
foo = "bar"?
baz = "qux"!
```

**Comment by AndrewRadev** [comment]
Good catch :). I've pushed a commit that should fix this, could you try it out?

**Comment by tsigo** [comment]
@AndrewRadev Works great, thanks!
