### ISSUE TITLE
Varying case lists

### ISSUE THREAD

**Issue by maxfl** [AndrewRadev/switch.vim#35]
I've tried to implement LaTeX font size commands switching which contains `\large`, `\Large`, `\LARGE` sequence. It seems that `switch.vim` can not correctly handle them.

Here is MWE:
```vim
        let g:switch_custom_definitions =
            \ [
            \   [ 'test', 'Test', 'TEST' ],
            \ ]
```
Not depending on the initial word, it switches to `Test` and stops there.

**Comment by AndrewRadev** [comment]
I think I figured it out -- it's probably a problem with `ignorecase`. I've pushed a commit that should fix the issue, could you try it out?

**Comment by maxfl** [comment]
Now it works. Thank you!
