### ISSUE TITLE
plugin works if opening a file from command line, doesn't work if opening a file from vim

### ISSUE THREAD

**Issue by szilveszter9** [AndrewRadev/switch.vim#44]
Hi Andrew,

First of all, many thanks for your effort building and maintaining this project.

I've played a bit a few months ago and just came back to it and realized that is not working if I open a file from vim.

1) I start vim in my terminal and open a file from vim using `:e /path/to/file`
- this case Switch plugin won't work - eg. not changing 'foo' to 'bar', seemingly has no effect at all
2) I start vim in my terminal passing /path/to/file as an argument `vim /path/to/file`
- Switch plugin works as intended

I tried with this minimal 4 lines .vimrc
```
     call plug#begin('~/.vim/plugged')
        Plug 'AndrewRadev/switch.vim'
     call plug#end()
       let b:switch_custom_definitions = [ ['foo', 'bar', 'baz'] ]
```

Thanks,
Szilveszter

vim: 8.0.494 compiled from source using `./configure --enable-python3interp=dynamic --enable-cscope --enable-rubyinterp --without-x --disable-gui && make && sudo make install`
Switch: latest version ddc069787c98ab90580667062908750257f43a34

**Comment by szilveszter9** [comment]
I've found if I am using
`let g:switch_custom_definitions`
instead of
`let b:switch_custom_definitions`
then Switch works fine even if I open the file from vim.

**Comment by AndrewRadev** [comment]
I think I understand the problem. The custom definitions you've created with `b:switch_custom_definitions` are buffer-local. That's what the `b:` prefix means. You can find more information on the topic with `:help b:`.

Basically, if you wanted to only define switches for a particular filetype, you would use the `b:` variant. I guess I hadn't explained it well enough in the documentation, so I added some more information about it: https://github.com/AndrewRadev/switch.vim/blob/f9826833a84d600811d4214059e30e2892c24dbf/doc/switch.txt#L162-L170

Does this solve your issue?

**Comment by szilveszter9** [comment]
Yes, that is perfect. Thanks a lot!
