### ISSUE TITLE
help with a bash switch?

### ISSUE THREAD

**Issue by divramod** [AndrewRadev/switch.vim#55]
Hey Andrew, i really like your plugin! Thx for the awesome work! I use it many times daily.

Now i wanted to ask you, if you can help me with a bash switch.

I want to switch between the following variable declarations:

```bash
"${test_var}"
${test_var}
$test_var
```
The declarations could be placed everywhere.

Is that one easy for you?

Thx again for the plugin!

**Comment by AndrewRadev** [comment]
> Hey Andrew, i really like your plugin! Thx for the awesome work! I use it many times daily.

Thank you for the kind words :).

> I want to switch between the following variable declarations:

Try putting this in `~/.vim/ftplugin/sh.vim`, so it gets run for every bash file:

``` vim
let b:switch_custom_definitions =
      \ [
      \   {
      \     '$\(\k\+\)':     '${\1}',
      \     '${\(\k\+\)}':   '"${\1}"',
      \     '"${\(\k\+\)}"': '$\1',
      \   }
      \ ]
```

The first transforms "$ followed by only keyword characters` into `${..}`, the second matches `$, then {, then keyword characters, then }`, and you can guess the third.

**Comment by divramod** [comment]
Hey Andrew,

thx for your fast reply!

i tested it and it has a little problem with underscores in the var name.

```
"${OPT_PATH_PATCH}"
```

is switching to 

```
"${OPTPATHPATCH}"
```

do you have a hint on how to make it underscore aware?

i will only use uppercase and lowercase letters and underscores in my variable names.

thx again!

**Comment by AndrewRadev** [comment]
To me, this seems like a conflict with some other switch mapping is it possible you have the example from the documentation installed that transforms `snake_case` into `camelCase`? As I said in the docs:

> Note that this particular example is NOT included as a built-in, since it may overshadow other ones and is probably not that useful, either

I'd recommend you only add that example as a buffer-local one for filetypes you tend to use it often, or add it with a different mapping, like I suggest here: https://github.com/AndrewRadev/switch.vim/blob/8f76655de1e3f3a0d45da4d779c54d30c4c5c0c1/doc/switch.txt#L295-L306.

Did I guess correctly what the problem might be?

**Comment by divramod** [comment]
you were right.

i have it running now.

thx a lot!

this will really give me a timeboost :-)

**Comment by divramod** [comment]
you will get a beer on the next chaos communication camp.

i learned vim in one of your courses at ohm ;-)

**Comment by AndrewRadev** [comment]
Excellent, I'm glad to hear I've been managing to recruit people to the Vim side :D. I'll try to remember to collect that beer!
