### ISSUE TITLE
Add case insesitivity

### ISSUE THREAD

**Issue by wsistyrud** [AndrewRadev/switch.vim#57]
It would be neat if adding
```
let g:switch_custom_definitions =
    \ [
    \   ['foo', 'bar', 'baz']
    \ ]
```
would also handle
`Foo -> Bar`
`FOO -> BAR`
etc. without having to specify all cases for each entry.
This is implemented in Toggle.vim

**Comment by AndrewRadev** [comment]
Would this functionality work for your use cases? https://github.com/AndrewRadev/switch.vim/blob/ec2b710739ec08e7a6a074ac4959b5d777bbbde1/doc/switch.txt#L187-L201

For longer explanations on casing, take a look at https://github.com/AndrewRadev/switch.vim/issues/28 and/or https://github.com/AndrewRadev/switch.vim/issues/1#issuecomment-8469462

**Comment by wsistyrud** [comment]
That was exactly what I was looking for. Thank you!
