### ISSUE TITLE
Does not working eruby_tag_type in eruby filetype.

### ISSUE THREAD

**Issue by seiyeah78** [AndrewRadev/switch.vim#59]
I want use ```Switch``` command at eruby tag. e.g. ``` <%= 'Hello, World!' %>```
But it is not working.
Looking at the result of ```b:switch_definitions```, the result is the same as that of filetype ruby.
<img width="970" alt="スクリーンショット 2020-01-08 1 17 38" src="https://user-images.githubusercontent.com/6185139/71910125-ae844600-31b4-11ea-8692-40e8000b19ca.png">

Do you have any solutions?

**Comment by AndrewRadev** [comment]
Could you tell me what the filetype is? For me, for a file named `test.erb`, I get the filetype `eruby` and the contents of `b:switch_definitions` is the eruby ones. Is it possible your file extension is different and/or the detected filetype is different?

**Comment by seiyeah78** [comment]
filetype is "eruby" when I open file "test.erb"

I checked in the following steps.

1. type ```nvim -N -u .test_vimrc -i NONE test.erb```
1. move cursor to ```=``` of ```<%= 'Hello, World!' %>```
1. execute ```:Switch``` command.

.test_vimrc
```vimscript
set rtp+=~/.vim/plugged/vim-plug
call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-plug',
      \ {'dir': '~/.vim/plugged/vim-plug/autoload'}

Plug 'itchyny/lightline.vim'
Plug 'AndrewRadev/switch.vim'
call plug#end()
```
screen capture
![not_working](https://user-images.githubusercontent.com/6185139/72357828-f8c67380-372e-11ea-87d7-a83e15064b9d.gif)

**Comment by AndrewRadev** [comment]
Thanks, I can replicate this now -- it's a matter of load order. I think I wasn't getting it, because I have vim-ruby installed locally, and it probably gets evaluated before the eruby stuff. Not 100% sure.

Well, either way, I've added a check to avoid it. Could you try again and let me know if it works correctly for you now?

**Comment by seiyeah78** [comment]
@AndrewRadev 
I'm sorry for the late reply.

I updated this plugin including [this commit.](https://github.com/AndrewRadev/switch.vim/commit/49c0efffc49e65126d823ced71e3edcb57c68cfb)

It works correctly!!
Of course, it works even if you install vim-ruby locally.
Thank you for resolving this issue!
