### ISSUE TITLE
"." repeats always forward, even if the last used command was "SwitchReverse"

### ISSUE THREAD

**Issue by KnoP-01** [AndrewRadev/switch.vim#71]
Hello,

I'd like to suggest the following change:

```vim
function! s:SwitchReverse()
  silent call switch#Switch({'reverse': 1})
  silent! call repeat#set(":Switch\<cr>")
endfunction
```

to

```vim
function! s:SwitchReverse()
  silent call switch#Switch({'reverse': 1})
  silent! call repeat#set(":SwitchReverse\<cr>") " <- Change here
endfunction
```

I can create a pull request if favored.

**Comment by AndrewRadev** [comment]
That's a good catch, thanks -- I think your suggestion is definitely the correct way it should go. I've made the change and used the chance to add some tests for repeating. Could you confirm that it works as you expect now?

**Comment by KnoP-01** [comment]
works as expected. Thank you!
