### ISSUE TITLE
Undefined variable: g:switch_builtins and invalid expression error on startup when opening a Ruby file and loading the plugin through NeoBundle

### ISSUE THREAD

**Issue by ravicious** [AndrewRadev/switch.vim#72]
I'm using neovim 0.4.3.

After updating switch.vim, I started getting the following error on startup when opening a Ruby file:

```
Error detected while processing /Users/rav/.vim/bundle/switch.vim/ftplugin/ruby/switch.vim:
line   21:                                                                                                    
E121: Undefined variable: g:switch_builtins
E15: Invalid expression: [   g:switch_builtins.ruby_hash_style,   g:switch_builtins.ruby_oneline_hash,   g:switch_buil
tins.ruby_lambda,   g:switch_builtins.ruby_if_clause,   g:switch_builtins.rspec_should,   g:switch_builtins.rspec_expe
ct,   g:switch_builtins.rspec_to,   g:switch_builtins.rspec_be_truthy_falsey,   g:switch_builtins.ruby_string,   g:swi
tch_builtins.ruby_short_blocks,   g:switch_builtins.ruby_array_shorthand,   g:switch_builtins.ruby_fetch,   g:switch_b
uiltins.ruby_assert_nil ]
```

I tried commenting out all plugins, removing them from the bundle directory, but the error was still there.

I created an empty vimrc which only sourced switch.vim and the error was gone. After I removed NeoBundle code from my vimrc and directly sourced only switch.vim, the error was also gone.

So I went to do a git bisect, because the plugin worked without problems before updating it to recent master. I found that the commit 2bf6516ec1f45e67b2c5 is the problematic one.

However, I have no idea how to further debug this. Any pointers will be appreciated!

**Comment by AndrewRadev** [comment]
I think I can guess what the problem might be. I think maybe NeoBundle is trying to lazy-load the plugin, but it still adds its ftplugin folders to the runtimepath. I feel like it probably should be able to handle the situation, but I've pushed a check in the filetype code in case the plugin wasn't loaded. Could you try it again and let me know if it works for you now?

**Comment by ravicious** [comment]
It works now! 77fb71952e7 fixed it, thanks!
