### ISSUE TITLE
Enable js toggles for typescript, typescript.tsx filetypes

### ISSUE THREAD

**Issue by unphased** [AndrewRadev/switch.vim#73]
Meanwhile my workaround is to add ["const", "let"] to g:switch_custom_definitions.

**Comment by AndrewRadev** [comment]
I've added support for the `javascriptreact`, `typescript`, and `typescriptreact` filetypes -- let me know if they get correctly detected for you.

**Comment by unphased** [comment]
Confirmed working! Thanks.
