### ISSUE TITLE
increase/decrease number

### ISSUE THREAD

**Issue by D1mon** [AndrewRadev/switch.vim#75]
increase: 1 -> 2 -> 3
decrease: 3 <- 2 <- 1

**Comment by AndrewRadev** [comment]
As far as I know, there's built-in mappings that do this: [`:help CTRL-A`](https://vimhelp.org/change.txt.html#CTRL-A). Or do you have something different in mind?

**Comment by D1mon** [comment]
Yes. this is it. I did not know. Thanks!

**Comment by zlksnk** [comment]
@AndrewRadev just on the same line, is it possible to do a increment/decrement on roman numeral (i, ii, iii, iv...) with switch.vim? This is somehow possible using [CtrlXA](https://github.com/Konfekt/vim-CtrlXA/) plugin.
