### ISSUE TITLE
Introduce a way to set priority/precedence?

### ISSUE THREAD

**Issue by unphased** [AndrewRadev/switch.vim#80]
If we have a situation in which two switch operations could happen based on where the cursor is, it is ambiguous which switch is performed. I'm currently using this magical gist https://gist.github.com/othree/5655583 and currently (as an example...) I want to introduce a switch that toggles between a type `T` and its `const T&` counterpart for C++ but what happens is that if my cursor is on top of the type name it will of course run the fancy change-variable-case-style switch. I'd like to make it so that the change-variable-case-style switch is the lowest priority, rather than as it is now where I would basically be experiencing more pressure to delete it as I begin to use switch more heavily. 

Although it works just fine to move the cursor to a suitable place it picks up the other switch and does the right thing. But it's not exactly ideal.

What do you think? This should not introduce much of a performance hit. 

Actually, I'm going to go and play around with reordering the `g:switch_custom_definitions` list order, it may be possible to control priority inherently by ordering the definition.

**Comment by unphased** [comment]
I tested reversing the order in the list and unfortunately it still grabbed the shorter inner match. I was hoping that it might just take the first match in the list and run with it, which would allow for superior control.

**Comment by unphased** [comment]
Some quick hunting in code reveals `switch#match#IsBetter`, maybe we can just add a config option to make it dumber and just scan the matches in order of declaration and short circuit?

**Comment by AndrewRadev** [comment]
There already is a config option that does that: https://github.com/AndrewRadev/switch.vim/blob/c534f11eb5f7b40336087b95dffd3db4adc04f0c/doc/switch.txt#L813-L819

You can try it out, my personal thinking is it would end up causing weird issues, but it was added by request, and I haven't heard about problems, so who knows :)

**Comment by unphased** [comment]
That's spectacular, and I'll report back the results in particular if it results in other problems.

**Comment by unphased** [comment]
I was able to get my desired behavior working with the following config: 

```viml
au FileType cpp let g:switch_custom_definitions = [ 
        \   switch#Words(['public', 'private']),
        \   switch#Words(['first', 'second']),
        \ {
          \  'const \([A-Za-z][A-Za-z0-9_:]*\)&': '\1'
        \ },
        \ {
          \  '\([A-Za-z][A-Za-z0-9_:]*\)' : 'const \1&'
        \ }
      \ ] + g:switch_custom_definitions

let g:switch_find_smallest_match = 0
```

However when I set them inside as a pair, like this: 

```viml
        \ {
          \  'const \([A-Za-z][A-Za-z0-9_:]*\)&': '\1',        
          \  '\([A-Za-z][A-Za-z0-9_:]*\)' : 'const \1&'
        \ },
```

it does not work properly, it will just keep matching the inner one so instead of toggling the const-refness of a type it will just continually add `const` to the front and `&` to the end. 

Could you help me figure out why it behaves that way?

**Comment by AndrewRadev** [comment]
This can't work, because both a variable starting with `const` and a variable *not* starting with `const` match `\([A-Za-z][A-Za-z0-9_:<>]*\)`. If you'd like to make these two work together, you need to add a "not starting with const" clause:

``` vim
au FileType cpp let g:switch_custom_definitions = [
        \   switch#Words(['public', 'private']),
        \   switch#Words(['first', 'second']),
        \ {
          \  'const \([A-Za-z][A-Za-z0-9_:<>]*\)&': '\1',
          \  '\%(const \)\@!\([A-Za-z][A-Za-z0-9_:<>]*\)' : 'const \1&'
        \ }
      \ ] + g:switch_custom_definitions " this has the other switches that I want to be lower precedence
```

I've got an explanation for a similar case in the documentation: https://github.com/AndrewRadev/switch.vim/blob/d9a8cf6171a4ac262c1cf4795984091b61989785/doc/switch.txt#L256-L271

**Comment by unphased** [comment]
Thank you!

One last question: Given the above revelations I can carefully order my switches in terms of priority, which is working well. However, all custom definitions seem to take priority over builtin ones, so now I'm struggling with how to convince it to prioritize the `true`/`false` switch over my const ref one in cpp files. What do you think? Maybe I just add it as another switch#Words entry?

**Comment by AndrewRadev** [comment]
If you've already put in the work to order things by priority, you could skip the built-in list altogether and try to pick only the parts that interest you. All the definitions are located in a big dictionary: https://github.com/AndrewRadev/switch.vim/blob/d9a8cf6171a4ac262c1cf4795984091b61989785/plugin/switch.vim#L21-L221

So you could, for example, add `g:switch_builtins.true_false` to your list. But I guess you also want to *stop* the built-ins from being loaded, which you can achieve by setting `g:switch_no_builtins` to 1: https://github.com/AndrewRadev/switch.vim/blob/d9a8cf6171a4ac262c1cf4795984091b61989785/doc/switch.txt#L358-L374

Would that work for your use cases?

**Comment by unphased** [comment]
That would definitely appear to work for me, thank you for the details! Gosh if only all software maintainers would approach things like you do... programming would be a much more pleasurable trade.

The ` switch#NormalizedCaseWords(['yes', 'no']),` that I have put into my `g:switch_custom_definitions` works fine. 

What I was originally looking for was essentially something I can inject into a specific spot in my ordered list in `g:switch_custom_definitions`. But what you've provided is superior to that because now I have the tools to programmatically take `g:switch_builtins` and turn it from a dict and splice it into my list at that location, and should I find a desire to further breakdown or adjust their priority order I could customize it straightforwardly as you described.

There's no need for me to stop the built-ins from being loaded as yet since they're only really being trampled by my overzealous const ref switch which only applies to the cpp filetype. I would imagine that in order to have the builtins available to use on other filetypes i should not set `g:switch_no_builtins` as the environment is shared by vim buffers (that is my understanding of the `g:` VimL variable scoping). 

Thanks for the assistance :)
