### ISSUE TITLE
Comparison to swapit

### ISSUE THREAD

**Issue by TamaMcGlinn** [AndrewRadev/switch.vim#83]
How does this plugin compare to [swapit](https://github.com/mjbrownie/swapit)? The stated goal is the same

See [converse question](https://github.com/mjbrownie/swapit/issues/33)

**Comment by AndrewRadev** [comment]
I've put in quite a lot of work in documenting the plugin. Particularly the "customization" and "built-ins" sections in the README (and in the Vim help docs) should be enough to make a comparison with swapit's features. Is there anything you find unclear in the docs?

**Comment by AndrewRadev** [comment]
I'll close this, since it doesn't seem like there's anything for me to do on it.
