### ISSUE TITLE
can you please add a configuration example for lua

### ISSUE THREAD

**Issue by divramod** [AndrewRadev/switch.vim#84]
hey,

i used switch.vim for the last years. 
i recently switched to configuring nvim with lua.
can you maybe add a lua example to the readme?

thx for the plugins you are writing!

**Comment by AndrewRadev** [comment]
The way to configure switch.vim is to set certain global variables to certain values. There's really nothing special to do -- you could find out how to set Vim global variables using the lua api and do that.

**Comment by unphased** [comment]
So I am trying to set up Lazy.nvim with a fresh clean lua config, and I do have Switch installed and I can see that it has created the normal mode map for `gs` to be `<Plug>(Switch)`, but typing gs doesn't do anything.
